//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalEventNepal.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalEventNepal.Resource.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        public static string AllEvents {
            get {
                return ResourceManager.GetString("AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attract and engage event attendees.
        /// </summary>
        public static string AttractEngageText {
            get {
                return ResourceManager.GetString("AttractEngageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to top.
        /// </summary>
        public static string BackToTop {
            get {
                return ResourceManager.GetString("BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click, Create and publish your events in just minutes..
        /// </summary>
        public static string ClickCreatePublishText {
            get {
                return ResourceManager.GetString("ClickCreatePublishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Event.
        /// </summary>
        public static string CreateAnEvent {
            get {
                return ResourceManager.GetString("CreateAnEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, Manage &amp; Market your event.
        /// </summary>
        public static string CreateManageMarketText {
            get {
                return ResourceManager.GetString("CreateManageMarketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an Event.
        /// </summary>
        public static string FindAnEvent {
            get {
                return ResourceManager.GetString("FindAnEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and attend events near you.
        /// </summary>
        public static string FindAttendEvent {
            get {
                return ResourceManager.GetString("FindAttendEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find events near you.
        /// </summary>
        public static string FindEventsNearYou {
            get {
                return ResourceManager.GetString("FindEventsNearYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Event Nepal Co..
        /// </summary>
        public static string GlobalEventNepalCompany {
            get {
                return ResourceManager.GetString("GlobalEventNepalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Events Nepal.
        /// </summary>
        public static string GlobalEventsNepal {
            get {
                return ResourceManager.GetString("GlobalEventsNepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the organization is a charity, government organization, sports league, corporation or any other group or organization, we help ensure successful events. We help expand event turnout, participation and engagement,and maximize commercial goals of the event through a wide range of online revenue generating functions..
        /// </summary>
        public static string HomePageBottomText {
            get {
                return ResourceManager.GetString("HomePageBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know what&apos;s happening in Nepali communities around the world.
        /// </summary>
        public static string KnowWhatsHappeningText {
            get {
                return ResourceManager.GetString("KnowWhatsHappeningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market your events.
        /// </summary>
        public static string MarketYourEvent {
            get {
                return ResourceManager.GetString("MarketYourEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organized by.
        /// </summary>
        public static string OrganizedBy {
            get {
                return ResourceManager.GetString("OrganizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal for Global Nepali Events.
        /// </summary>
        public static string PortalToGEN {
            get {
                return ResourceManager.GetString("PortalToGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        public static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
    }
}
